{{- range $name, $svc := .Values.services }}
{{- if not $svc.disabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.namespace }}
  labels: {{- include "iicpc.labels" (dict "Root" $ "Name" $name) | nindent 4 }}
{{- end }}
{{- end }}
