apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iicpc-contestants

resources:
  - isolate-policy.yaml
  - pumba-network-delay.yaml

commonLabels:
  app.kubernetes.io/component: chaos
  app.kubernetes.io/managed-by: kustomize
